services:
  redis:
    image: redis:7.0
    container_name: managementproject-redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: managementproject-web
    command: gunicorn managementproject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    container_name: managementproject-celery
    command: celery -A managementproject worker --loglevel=info
    depends_on:
      - redis
      - web

  beat:
    build: .
    container_name: managementproject-beat
    command: celery -A managementproject beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
